name: GCP deployment

on:
  push:
    branches:
      - master  # only executing when merge on main branch

jobs:
  gcp-deployment:
    name: Build and push image, deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      #SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      REGION: europe-west1
      REPOSITORY: docker-artifact-regsitry
      IMAGE: src_ftbl_home_project

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.7.0
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        create_credentials_file: true
        cleanup_credentials: true

      # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

      # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker
      run: |
        gcloud auth configure-docker -q

    - name: Build docker image
      run: |-
        docker build -t "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest" .

    - name: Authenticating docker with gcloud
      run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin "https://$REGION-docker.pkg.dev"

    - name: Push image to Google Artifact Registry repository
      run: |-
        docker push "$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest"
      if: success()


    - name: Deploy app to cloud run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: "prod-playground"
        image: "${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}:latest"
        region: "${{ env.REGION }}"
